#
# Copyright (C) 2022 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

site_name: dd-vault-catalog
theme:
  name: readthedocs

repo_name: DANS-KNAW/dd-vault-catalog
repo_url: https://github.com/DANS-KNAW/dd-vault-catalog

nav:
  - Manual:
      - Description: index.md
      - Installation: installation.md
      - Configuration: config.md
      - API: to-api.md
      - Context: context.md
  - Development:
      - Overview: dev.md

extra:
  data_vault_storage_root_url: https://dans-knaw.github.io/dans-datastation-architecture/data-vault-storage-root/


plugins:
  - markdownextradata
  - search

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
      use_pygments: False
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: True

